### ISSUE TITLE
Examples and simple usages

### ISSUE THREAD

**Issue by fxfactorial** [mirage/mirage-profile#15]
Cool concept and looks greatly. 

I want to use this without mirage, with just a plain OCaml lwt based program, is that not possible?

And if it is  can you provide a complete self-contained example?

**Comment by talex5** [comment]
Just follow the instructions in the README under **To trace a Unix process**.

**Comment by fxfactorial** [comment]
I guess I should have written that I did read the readme. All I see is: 

```ocaml
To trace a Unix process, use MProf_unix.mmap_buffer to write to an mmapped file:

let () =
  let buffer = MProf_unix.mmap_buffer ~size:1000000 "trace.ctf" in
  let trace_config = MProf.Trace.Control.make buffer MProf_unix.timestamper in
  MProf.Trace.Control.start trace_config
```

No mention at all of where MProf_unix comes from or how to compile it. Does the M mean mirage only? No mention at all. I assume it comes from the forked version of Lwt.

Okay, but I can stumble my way across to try this

```shell
ocamlfind ocamlopt -linkpkg m.ml -linkpkg lwt.tracing,lwt.unix -o F                               ⏎
File "m.ml", line 2, characters 15-37:
Error: Unbound module Prof_Unix
```

Great, and now I give up on this library. 

I understand this is free software and thank you for this effort, but can we please try to assume that readers don't have Ph.Ds, don't know know the nuances of using OCaml building, aka ocamlfind etc and have actually tried reading the README rather than just tell people rtfm and just close issues.

**Comment by talex5** [comment]
You should have a `mirage-profile.unix` ocamlfind library. e.g. I have:

    $ ocamlfind list|grep mirage-profile
    mirage-profile      (version: 0.6.1)
    mirage-profile.unix (version: 0.6.1)
    mirage-profile.xen  (version: 0.6.1)

You can also run the example in the `test` directory:

    $ ./configure --enable-tests
    $ make test

**Comment by fxfactorial** [comment]
~ ❯❯❯ ocamlfind list | grep mirage-profile                                                              ⏎
mirage-profile      (version: 0.6.1)
mirage-profile.unix (version: 0.6.1)
~ ❯❯❯ ocamlfind ocamlopt -linkpkg m.ml -linkpkg lwt.tracing,lwt.unix,mirage-profile.unix -o F
File "m.ml", line 2, characters 15-37:
Error: Unbound module MProf_unix

**Comment by talex5** [comment]
You still need the `M` in `MProf`. It should look like this:

https://github.com/mirage/mirage-profile/blob/e08a9e56b61adfa685ae6f4ecbd8b24c1e7c3874/test/benchmark.ml#L40

(uncomment the `mmap_buffer` line to export the results)

**Comment by fxfactorial** [comment]
Thank you, got it compiled and ran it.
