### ISSUE TITLE
opam uninstall unreliable?

### ISSUE THREAD

**Issue by djs55** [mirage/mirage-profile#16]
In mirage/mirage#485, [travis failed](https://travis-ci.org/mirage/mirage/jobs/105480610)

```
[WARNING] failure in package uninstall script, some files may remain:
          # opam-version 1.2.2
          # os           linux
          # command      ocamlfind remove mirage-profile
          # path         /home/travis/.opam
          # compiler     system (4.01.0)
          # exit-code    2
          # env-file     /home/travis/.opam/log/log-8897-062a54.env
          # stdout-file  /home/travis/.opam/log/log-8897-062a54.out
          # stderr-file  /home/travis/.opam/log/log-8897-062a54.err
          ### stderr ###
          # ocamlfind:
          /home/travis/.opam/system/lib/stublibs/dllvchan_stubs.so.owner: No
          such file or directory
[WARNING] Directory /home/travis/.opam/system/lib/mirage-profile is not empty,
          not removing
```

**Comment by talex5** [comment]
/home/travis/.opam/system/lib/stublibs/dllvchan_stubs.so.owner: No such file or directory

This file isn't anything to do with mirage-profile. Perhaps two uninstall processes ran concurrently and one deleted this file while another tried to read it?

**Comment by djs55** [comment]
There's nothing wrong with the uninstall runes here, since it's all done via `topkg` and `.install` files I think.

**Comment by yomimono** [comment]
See https://gitlab.camlcity.org/gerd/lib-findlib/issues/9 ; this is fixed in findlib master but possibly not released yet.  At any rate, not a `mirage-profile` or `vchan` bug.

**Comment by djs55** [comment]
Interesting!
