### ISSUE TITLE
Rebase to 2.4.7

### ISSUE THREAD

**Issue by samoht** [mirage/mirage-profile#8]
Not sure if it is the right place to report this, but the `#tracing` branch of Lwt is a bit outdated. Could it be possible to rebase it the the most recent lwt (2.4.7)?

See https://github.com/talex5/lwt/commit/25a691d6bc73673ef00f1f7ac5ccc096cb638332#commitcomment-9543894

**Comment by talex5** [comment]
Done: https://github.com/mirage/lwt/commits/tracing

**Comment by samoht** [comment]
Thanks!
